/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hqsphkdwkncmsxqrhmly"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxc3Boa2R3a25jbXN4cXJobWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4OTE5NzUsImV4cCI6MjA4MDQ2Nzk3NX0.lbOlEVp-cwpzw-oDU6_X4a5TA7bc3rXJxvR3s7IS5fU"